import { Injectable } from '@angular/core';

export interface TabCodigos {
  codDescricao: string;
  amparo: string;
  gravidade: string;
  valor: number;
  competencia: string;
}

@Injectable({
  providedIn: 'root'
})
export class CodigosInfraService {
  private codigos: TabCodigos[] = [
    {
      codDescricao: '7480-1 | Aprovar proj edificação pólo atrativo trânsito s/ anuência órgão/entid trânsito',
      amparo: '93 c/c 95, § 4º',
      gravidade: '---',
      valor: 0,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7480-2 | Aprovar proj edificação pólo atrativo trâns s/ estacion/indicação vias de acesso',
      amparo: '93 c/c 95, § 4º',
      gravidade: '---',
      valor: 0,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7498-0 | Ñ sinalizar devida/imed obstáculo à circul/segurança veíc/pedestre pista/calçada',
      amparo: '94',
      gravidade: '---',
      valor: 0,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7501-0 | Utilizar ondulação transversal/sonorizador fora padrão/critério estab p/ Contran',
      amparo: '94, § único',
      gravidade: '---',
      valor: 0,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7510-1 | Iniciar obra perturbe/interrompa circulação/segurança veíc/pedestres s/permissão',
      amparo: '95',
      gravidade: '---',
      valor: 0,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7510-2 | Iniciar evento perturbe/interrompa circulaç/segurança veíc/pedestres s/permissão',
      amparo: '95',
      gravidade: '---',
      valor: 0,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7528-1 | Não sinalizar a execução ou manutenção da obra',
      amparo: '95, § 1º',
      gravidade: '---',
      valor: 0,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7528-2 | Não sinalizar a execução ou manutenção do evento',
      amparo: '95, § 1º',
      gravidade: '---',
      valor: 0,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7536-0 | Não avisar comunidade c/ 48h antec interdição via indicando caminho alternativo',
      amparo: '95, § 2º',
      gravidade: '---',
      valor: 0,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5010-0 | Dirigir veículo sem possuir CNH ou Permissão para Dirigir',
      amparo: '162, I',
      gravidade: '7 - Gravíss 3X',
      valor:  574.62,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5029-1 | Dirigir veículo com CNH ou PPD cassada',
      amparo: '162, II',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5029-2 | Dirigir veículo com CNH ou PPD com suspensão do direito de dirigir',
      amparo: '162, II',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5037-1 | Dirigir veículo com CNH de categoria diferente da do veículo',
      amparo: '162, III',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5037-2 | Dirigir veículo com PPD de categoria diferente da do veículo',
      amparo: '162, III',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5045-0 | Dirigir veículo com validade de CNH/PPD vencida há mais de 30 dias',
      amparo: '162, V',
      gravidade: '7 - Gravíss',
      valor:  191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5053-1 | Dirigir veículo sem usar lentes corretoras de visão',
      amparo: '162, VI',
      gravidade: '7 - Gravíss',
      valor:  191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5053-2 | Dirigir veículo sem usar aparelho auxiliar de audição',
      amparo: '162, VI',
      gravidade: '7 - Gravíss',
      valor:  191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5053-3 | Dirigir veículo sem usar aparelho auxiliar de prótese física',
      amparo: '162, VI',
      gravidade: '7 - Gravíss',
      valor:  191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5053-4 | Dirigir veículo s/ adaptações impostas na concessão/renovação licença conduzir',
      amparo: '162, VI',
      gravidade: '7 - Gravíss',
      valor:  191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5061-0 | Entregar veículo a pessoa sem CNH ou Permissão para Dirigir',
      amparo: '163 c/c 162, I',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5070-1 | Entregar veículo a pessoa com CNH ou PPD cassada',
      amparo: '163 c/c 162, II',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5070-2 | Entregar veículo a pessoa com CNH ou PPD com suspensão do direito de dirigir',
      amparo: '163 c/c 162, II',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5088-1 | Entregar veículo a pessoa com CNH de categoria diferente da do veículo',
      amparo: '163 c/c 162, III',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5088-2 | Entregar veículo a pessoa com PPD de categoria diferente da do veículo',
      amparo: '163 c/c 162, III',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5096-0 | Entregar veículo a pessoa com CNH/PPD vencida há mais de 30 dias',
      amparo: '163 c/c 162, V',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5100-1 | Entregar o veículo a pessoa sem usar lentes corretoras de visão',
      amparo: '163 c/c 162, VI',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5100-2 | Entregar o veículo a pessoa sem usar aparelho auxiliar de audição ',
      amparo: '163 c/c 162, VI',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5100-3 | Entregar o veículo a pessoa sem aparelho de prótese física',
      amparo: '163 c/c 162, VI',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5100-4 | Entregar veíc pessoa s/ adaptações impostas concessão/renovação licença conduzir',
      amparo: '163 c/c 162, VI',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5118-0 | Permitir posse/condução do veículo a pessoa sem CNH ou PPD',
      amparo: '164 c/c 162, I',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5126-1 | Permitir posse/condução do veículo a pessoa com CNH ou PPD cassada',
      amparo: '164 c/c 162, II',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5126-2 | Permitir posse/condução veíc pessoa com CNH/PPD c/ suspensão direito de dirigir',
      amparo: '164 c/c 162, II',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5134-1 | Permitir posse/condução veíc a pessoa com CNH categoria diferente da do veículo',
      amparo: '164 c/c 162, III',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5134-2 | Permitir posse/condução veíc a pessoa com PPD categoria diferente da do veículo',
      amparo: '164 c/c 162, III',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5142-0 | Permitir posse/condução do veíc a pessoa com CNH/PPD vencida há mais de 30 dias',
      amparo: '164 c/c 162, V',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5150-1 | Permitir posse/condução do veículo a pessoa sem usar lentes corretoras de visão',
      amparo: '164 c/c 162, VI',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5150-2 | Permitir posse/condução do veículo a pessoa s/ usar aparelho auxiliar de audição',
      amparo: '164 c/c 162, VI',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5150-3 | Permitir posse/condução do veículo a pessoa sem usar aparelho de prótese física',
      amparo: '164 c/c 162, VI',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5150-4 | Permitir posse/cond veíc s/ adaptações impostas concessão/renovação licença cond',
      amparo: '164 c/c 162, VI',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5169-1 | Dirigir sob a influência de álcool',
      amparo: '165',
      gravidade: 'Gravíss 10X',
      valor: 1915.40,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5169-2 | Dirigir sob a influência de quer substância psicoativa que deter. dependência',
      amparo: '165',
      gravidade: 'Gravíss 10X',
      valor: 1915.40,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5177-0 | Confiar/entregar veíc pess c/ estado físico/psíquico s/ condições dirigir segur',
      amparo: '166',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '5185-1 | Deixar o condutor de usar o cinto segurança',
      amparo: '167',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5193-0 | Transportar criança sem observância das normas de segurança estabelecidas p/ CTB',
      amparo: '168',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5207-0 | Dirigir sem atenção ou sem os cuidados indispensáveis à segurança',
      amparo: '169',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5215-1 | Dirigir ameaçando os pedestres que estejam atravessando a via pública',
      amparo: '170',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5215-2 | Dirigir ameaçando os demais veículos',
      amparo: '170',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5223-1 | Usar veículo para arremessar sobre os pedestres água ou detritos',
      amparo: '171',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5223-2 | Usar veículo para arremessar sobre os veículos água ou detritos',
      amparo: '171',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5231-1 | Atirar do veículo objetos ou substâncias',
      amparo: '172',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5231-2 | Abandonar na via objetos ou substâncias',
      amparo: '172',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5240-0 | Disputar corrida',
      amparo: '173',
      gravidade: 'Gravíss 10X',
      valor: 1915.40,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5258-1 | Promover na via competição sem permissão',
      amparo: '174',
      gravidade: 'Gravíss 10X',
      valor: 1915.40,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5258-2 | Promover na via eventos organizados sem permissão',
      amparo: '174',
      gravidade: 'Gravíss 10X',
      valor: 1915.40,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5258-3 | Promover na via exibição e demonstração de perícia em manobra de veículo s/perm',
      amparo: '174',
      gravidade: 'Gravíss 10X',
      valor: 1915.40,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5266-1 | Participar na via como condutor em competição sem permissão',
      amparo: '174',
      gravidade: 'Gravíss 10X',
      valor: 1915.40,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5266-2 | Participar na via como condutor em eventos organizados sem permissão',
      amparo: '174',
      gravidade: 'Gravíss 10X',
      valor: 1915.40,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5266-3 | Participar como condutor exib/demonst perícia em manobra de veic s/ permissão ',
      amparo: '174',
      gravidade: 'Gravíss 10X',
      valor: 1915.40,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5274-1 | Utiliz veíc demonst/exibir manobra perigosa mediante arrancada brusca',
      amparo: '175',
      gravidade: 'Gravíss 10X',
      valor: 1915.40,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5274-2 | Utiliz veíc dem/exibir manob perig med derrap/frenag c/desliz/arrast pneus',
      amparo: '175',
      gravidade: 'Gravíss 10X',
      valor: 1915.40,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5282-0 | Deixar o cond envolvido em acidente, de prestar ou providenciar socorro a vítima',
      amparo: '176, I',
      gravidade: 'Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5290-0 | Deixar o cond envolvido em acid, de adotar provid p/ evitar perigo p/o trânsito',
      amparo: '176, II',
      gravidade: 'Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5304-0 | Deixar o cond envolvido em acidente, de preservar local p/ trab policia/pericia',
      amparo: '176, III',
      gravidade: 'Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5312-0 | Deixar o cond envolvido em acid, de remover o veíc local qdo determ polic/agente',
      amparo: '176, IV',
      gravidade: 'Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5320-0 Deixar o cond envolvido em acid, de identificar-se policial e prestar inf p/o BO',
      amparo: '176, V',
      gravidade: 'Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5339-0 | Deixar o cond de prestar socorro vítima acid de trânsito, qdo solicit p/ agente',
      amparo: '177',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5347-0 | Deixar o condutor envolvido em acidente s/ vítima, de remover o veículo do local',
      amparo: '178',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5355-0 | Fazer ou deixar que se faça reparo em veíc, em rodovia e via de trânsito rápido',
      amparo: '179, I',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5363-0 | Fazer/deixar que se faça reparo em veíc nas vias (q não rodovia/transito rapido)',
      amparo: '179, II',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5371-0 | Ter seu veículo imobilizado na via por falta de combustível',
      amparo: '180',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5380-0 | Estacionar nas esquinas e a menos de 5m do alinhamento da via transversal',
      amparo: '181, I',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5398-0 | Estacionar afastado da guia da calçada (meio-fio) de 50cm a 1m',
      amparo: '181, II',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5401-0 | Estacionar afastado da guia da calçada (meio-fio) a mais de 1m',
      amparo: '181, III',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5410-0 | Estacionar em desacordo com as posições estabelecidas no CTB',
      amparo: '181, IV',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5428-1 | Estacionar na pista de rolamento das estradas',
      amparo: '181, V',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5428-2 | Estacionar na pista de rolamento das rodovias',
      amparo: '181, V',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5428-3 | Estacionar na pista de rolamento das vias de trânsito rápido',
      amparo: '181, V',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5428-4 | Estacionar na pista de rolamento das vias dotadas de acostamento',
      amparo: '181, V',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5436-0 | Estacionar junto/sobre hidr de incêndio, reg de água/tampa de poço visit gal sub',
      amparo: '181, VI',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5444-0 | Estacionar nos acostamentos',
      amparo: '181, VII',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5452-1 | Estacionar no passeio',
      amparo: '181, VIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5452-2 | Estacionar sobre faixa destinada a pedestre',
      amparo: '181, VIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5452-3 | Estacionar sobre ciclovia ou ciclofaixa',
      amparo: '181, VIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5452-4 | Estacionar nas ilhas ou refúgios',
      amparo: '181, VIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5452-5 | Estacionar ao lado ou sobre canteiro central/divisores de pista de rolamento',
      amparo: '181, VIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5452-6 | Estacionar ao lado ou sobre marcas de canalização',
      amparo: '181, VIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5452-7 | Estacionar ao lado ou sobre gramado ou jardim público',
      amparo: '181, VIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5460-0 | Estacionar em guia de calçada rebaixada destinada à entrada/saída de veículos',
      amparo: '181, IX',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5479-0 | Estacionar impedindo a movimentação de outro veículo',
      amparo: '181, X',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5487-0 | Estacionar ao lado de outro veículo em fila dupla',
      amparo: '181, XI',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5495-0 | Estacionar na área de cruzamento de vias',
      amparo: '181, XII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5509-0 | Estacionar no ponto de embarque/desembarque de passageiros transporte coletivo',
      amparo: '181, XIII',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5517-1 | Estacionar nos viadutos',
      amparo: '181, XIV',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5517-2 | Estacionar nas pontes',
      amparo: '181, XIV',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5517-3 | Estacionar nos túneis',
      amparo: '181, XIV',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5568-0 | Estacionar local/horário de estacionamento e parada proibidos pela sinalização',
      amparo: '181, XIX',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5525-0 | Estacionar na contramão de direção',
      amparo: '181, XV',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5533-0 | Estacionar aclive/declive ñ freado e sem calço segurança, PBT superior a 3500kg',
      amparo: '181, XVI',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5541-1 | Estacionar em desacordo com a regulamentação especificada pela sinalização',
      amparo: '181, XVII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5541-2 | Estacionar em desacordo com a regulamentação - estacionamento rotativo',
      amparo: '181, XVII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5541-3 | Estacionar em desacordo com a regulamentação - ponto ou vaga de táxi',
      amparo: '181, XVII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5541-4 | Estacionar em desacordo com a regulamentação - vaga de carga/descarga',
      amparo: '181, XVII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5541-5 | Estacionar em desacordo com a regulamentação - vaga portador necessid especiais',
      amparo: '181, XVII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5541-6 | Estacionar em desacordo com a regulamentação - vaga idoso',
      amparo: '181, XVII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5541-7 | Estacionar em desacordo com a regulamentação - vaga de curta duração',
      amparo: '181, XVII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5550-0 | Estacionar em local/horário proibido especificamente pela sinalização',
      amparo: '181, XVIII',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5576-0 | Parar nas esquinas e a menos 5m do bordo do alinhamento da via transversal',
      amparo: '182, I',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5584-0 | Parar afastado da guia da calçada (meio-fio) de 50cm a 1m',
      amparo: '182, II',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5592-0 | Parar afastado da guia da calçada (meio-fio) a mais de 1m',
      amparo: '182, III',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5606-0 | Parar em desacordo com as posições estabelecidas no CTB',
      amparo: '182, IV',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5614-1 | Parar na pista de rolamento das estradas',
      amparo: '182, V',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5614-2 | Parar na pista de rolamento das rodovias',
      amparo: '182, V',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5614-3 | Parar na pista de rolamento das rodovias',
      amparo: '182, V',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5614-4 | Parar na pista de rolamento das demais vias dotadas de acostamento',
      amparo: '182, V',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5622-1 | Parar no passeio',
      amparo: '182, VI',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5622-2 | Parar sobre faixa destinada a pedestre',
      amparo: '182, VI',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5622-3 | Parar nas ilhas ou refúgios',
      amparo: '182, VI',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5622-4 | Parar nos canteiros centrais/divisores de pista de rolamento',
      amparo: '182, VI',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5622-5 | Parar nas marcas de canalização',
      amparo: '182, VI',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5630-0 | Parar na área de cruzamento de vias',
      amparo: '182, VII',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5649-1 | Parar nos viadutos',
      amparo: '182, VIII',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5649-2 | Parar nas pontes',
      amparo: '182, VIII',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5649-3 | Parar nos túneis',
      amparo: '182, VIII',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5657-0 | Parar na contramão de direção',
      amparo: '182, IX',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5665-0 | Parar em local/horário proibidos especificamente pela sinalização',
      amparo: '182, X',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5673-1 | Parar sobre faixa de pedestres na mudança de sinal luminoso',
      amparo: '183',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5673-2 | Parar sobre faixa de pedestres na mudança de sinal luminoso (fisc eletrônica)',
      amparo: '183',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5681-0 | Transitar na faixa/pista da direita regul circulação exclusiva determ veículo',
      amparo: '184, I',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5690-0 | Transitar na faixa/pista da esquerda regul circulação exclusiva determ veículo',
      amparo: '184, II',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7587-0 | Transitar na faixa ou via exclusiva regulam. p/ transp. públ. coletivo passag.',
      amparo: '184, III',
      gravidade: '7-Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5703-0 | Deixar de conservar o veículo na faixa a ele destinada pela sinalização de regul',
      amparo: '185, I',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5711-0 | Deixar de conservar nas faixas da direita o veículo lento e de maior porte',
      amparo: '185, II',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5720-0 | Transitar pela contramão de direção em via com duplo sentido de circulação',
      amparo: '186, I',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5738-0 | Transitar pela contramão de direção em via c/ sinalização de regul sentido único',
      amparo: '186, II',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5746-1 | Transitar em local/horário não permitido pela regul estabelecida p/ autoridade',
      amparo: '187, I',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5746-2 | Transitar em local/horário não permitido pela regulamentação - rodízio',
      amparo: '187, I',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5746-3 | Transitar em local/horário não permitido pela regulamentação - caminhão',
      amparo: '187, I',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5762-0 | Transitar ao lado de outro veículo, interrompendo ou perturbando o trânsito',
      amparo: '188',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5770-1 | Deixar de dar passagem a veíc precedido de batedores devidamente identificados',
      amparo: '189',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5770-2 | Deixar de dar passagem a veíc socorro incêndio/salv serv urgência devid identif',
      amparo: '189',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5770-3 | Deixar de dar passagem a veíc de polícia em serviço de urgência devid identif',
      amparo: '189',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5770-4 | Deixar de dar passagem a veíc de operação e fiscalização de trânsito devid ident',
      amparo: '189',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5770-5 | Deixar de dar passagem a ambulância em serviço de urgência devid identificada',
      amparo: '189',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5789-0 | Seguir veículo em serv urgência devid identific p/ alarme sonoro/ilum vermelha',
      amparo: '190',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5797-0 | Forçar passagem entre veícs trans sent opostos na iminência realiz ultrapassagem',
      amparo: '191',
      gravidade: 'Gravíss 10X',
      valor: 1915.40,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5800-0 | Deixar guardar dist segurança lat/front entre seu veíc e demais e ao bordo pista',
      amparo: '192',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5819-1 | Transitar com o veículo em calçadas, passeios',
      amparo: '193',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5819-2 | Transitar com o veículo em ciclovias, ciclofaixas',
      amparo: '193',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5819-3 | Transitar com o veículo em ajardinamentos, gramados, jardins públicos',
      amparo: '193',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5819-4 | Transitar com o veículo em canteiros centrais/divisores de pista de rolamento',
      amparo: '193',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5819-5 | Transitar com o veículo em ilhas, refúgios',
      amparo: '193',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5819-6 | Transitar com o veículo em marcas de canalização',
      amparo: '193',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5819-7 | Transitar com o veículo em acostamentos',
      amparo: '193',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5819-8 | Transitar com o veículo em passarelas',
      amparo: '193',
      gravidade: '7 - Gravíss 3X',
      valor: 574.62,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5827-0 | Transitar em marcha ré, salvo na distância necessária a pequenas manobras',
      amparo: '194',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5835-0 | Desobedecer às ordens emanadas da autorid compet de trânsito ou de seus agentes',
      amparo: '195',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5843-1 | Deixar de indicar c/ antec, med gesto de braço/luz indicadora, início da marcha',
      amparo: '196',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5843-2 | Deixar de indicar c/ antec, med gesto de braço/luz indicadora, manobra de parar',
      amparo: '196',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5843-3 | Deixar de indicar c/ antec, med gesto de braço/luz indicadora, mudança direção',
      amparo: '196',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5843-4 | Deixar de indicar c/ antec, med gesto de braço/luz indicadora, mudança de faixa',
      amparo: '196',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '5851-1 | Deixar de deslocar c/antecedência veíc p/ faixa mais à esquerda qdo for manobrar',
      amparo: '197',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5851-2 | Deixar de deslocar c/antecedência veíc p/ faixa mais à direita qdo for manobrar',
      amparo: '197',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5860-0 | Deixar de dar passagem pela esquerda quando solicitado',
      amparo: '198',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5878-0 | Ultrapassar pela direita, salvo qdo veíc da frente der sinal p/ entrar esquerda',
      amparo: '199',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5886-0 | Ultrap pela direita veíc transp colet/escolar parado para emb/desemb passageiros',
      amparo: '200',
      gravidade: '7 - Gravíss',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5894-0 | Deixar de guardar a distância lateral de 1,50m ao passar/ultrapassar bicicleta',
      amparo: '201',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5908-0 | Ultrapassar pelo acostamento',
      amparo: '202, I',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5916-1 | Ultrapassar em interseções',
      amparo: '202, II',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5916-2 | Ultrapassar em passagem de nível',
      amparo: '202, II',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5924-1 | Ultrapassar pela contramão nas curvas sem visibilidade suficiente',
      amparo: '203, I',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5924-2 | Ultrapassar pela contramão nos aclives ou declives, sem visibilidade suficiente',
      amparo: '203, I',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5932-0 | Ultrapassar pela contramão nas faixas de pedestre',
      amparo: '203, II',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5940-1 | Ultrapassar pela contramão nas pontes',
      amparo: '203, III',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5940-2 | Ultrapassar pela contramão nos viadutos',
      amparo: '203, III',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5940-3 | Ultrapassar pela contramão nos túneis',
      amparo: '203, III',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5959-1 | Ultrapassar pela contramão veículo parado em fila junto sinal luminoso',
      amparo: '203, IV',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5959-2 | Ultrapassar pela contramão veículo parado em fila junto a cancela/porteira',
      amparo: '203, IV',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5959-3 | Ultrapassar pela contramão veículo parado em fila junto a cruzamento',
      amparo: '203, IV',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5959-4 | Ultrapassar pela contramão veíc parado em fila junto qq impedimento à circulação',
      amparo: '203, IV',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5967-0 | Ultrapassar pela contramão linha de divisão de fluxos opostos, contínua amarela',
      amparo: '203, V',
      gravidade: '7 - Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5975-0 | Deixar de parar no acostamento à direita, p/ cruzar pista ou entrar à esquerda',
      amparo: '204',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5983-0 | Ultrapassar veículo em movimento que integre cortejo/desfile/formação militar',
      amparo: '205',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5991-0 | Executar operação de retorno em locais proibidos pela sinalização',
      amparo: '206, I',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6009-1 | Executar operação de retorno nas curvas',
      amparo: '206, II',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6009-2 | Executar operação de retorno nos aclives ou declives',
      amparo: '206, II',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6009-3 | Executar operação de retorno nas pontes',
      amparo: '206, II',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6009-4 | Executar operação de retorno nos viadutos',
      amparo: '206, II',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6009-5 | Executar operação de retorno nos túneis',
      amparo: '206, II',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6017-1 | Executar operação de retorno passando por cima de calçada, passeio',
      amparo: '206, III',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6017-2 | Executar operação de retorno passando por cima de ilha, refúgio',
      amparo: '206, III',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6017-3 | Executar operação de retorno passando por cima de ajardinamento',
      amparo: '206, III',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6017-4 | Executar operação de retorno passando por cima de canteiro de divisor de pista',
      amparo: '206, III',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6017-5 | Executar operação de retorno passando por cima de faixa de pedestres',
      amparo: '206, III',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6017-6 | Executar operação de retorno passando por cima de faixa de veíc não motorizados',
      amparo: '206, III',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6025-0 | Executar retorno nas interseções, entrando na contramão da via transversal',
      amparo: '206, IV',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6033-0 | Executar retorno c/prejuízo da circulação/segurança ainda que em local permitido',
      amparo: '206, V',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6041-1 | Executar operação de conversão à direita em local proibido pela sinalização',
      amparo: '207',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6041-2 | Executar operação de conversão à esquerda em local proibido pela sinalização',
      amparo: '207',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6050-1 | Avançar o sinal vermelho do semáforo',
      amparo: '208',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6050-2 | Avançar o sinal de parada obrigatória',
      amparo: '208',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6050-3 | Avançar o sinal vermelho do semáforo - fiscalização eletrônica',
      amparo: '208',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6068-1 | Transpor bloqueio viário com ou sem sinalização ou dispositivos auxiliares',
      amparo: '209',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '6068-2 | Deixar de adentrar às áreas destinadas à pesagem de veículos',
      amparo: '209',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '6068-3 | Evadir-se para não efetuar o pagamento do pedágio',
      amparo: '209',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '6076-0 | Transpor bloqueio viário policial',
      amparo: '210',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '6084-1 | Ultrapassar veículos motorizados em fila, parados em razão de sinal luminoso',
      amparo: '211',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '6084-2 | Ultrapassar veículos motorizados em fila, parados em razão de cancela',
      amparo: '211',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '6084-3 | Ultrapassar veíc motorizados em fila parados em razão de bloqueio viário parcial',
      amparo: '211',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '6084-4 | Ultrapassar veículos motorizados em fila, parados em razão de qualquer obstáculo',
      amparo: '211',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '6092-0 | Deixar de parar o veículo antes de transpor linha férrea',
      amparo: '212',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6106-0 | Deixar de parar sempre que a marcha for interceptada por agrupamento de pessoas',
      amparo: '213, I',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6114-0 | Deixar de parar sempre que a marcha for interceptada por agrupamento de veículos',
      amparo: '213, II',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6122-0 | Deixar de dar preferência a pedestre/veic ñ motorizado na faixa a ele destinada',
      amparo: '214, I',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6130-0 | Deixar de dar preferência a pedestre/veic ñ mot que ñ haja concluído a travessia',
      amparo: '214, II',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6149-0 | Deixar de dar preferência a pedestre port deficiência fís/criança/idoso/gestante',
      amparo: '214, III',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6157-0 | Deixar de dar preferência a pedestre/veic ñ mot qdo iniciada travessia s/sinaliz',
      amparo: '214, IV',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6165-0 | Deixar de dar preferência a pedestre/veic não mot atravessando a via transversal',
      amparo: '214, V',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6173-1 | Deixar de dar preferência em interseção ñ sinaliz, a veíc circulando por rodovia',
      amparo: '215, I, a',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6173-2 | Deixar de dar preferência em interseção ñ sinaliz, veíc circulando por rotatória',
      amparo: '215, I, a',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6173-3 | Deixar de dar prefer em interseção não sinalizada, a veículo que vier da direita',
      amparo: '215, I, b',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6181-0 | Deixar de dar preferência nas interseções com sinalização de Dê a Preferência',
      amparo: '215, II',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6190-0 | Entrar/sair área lindeira sem precaução com a segurança de pedestres e veículos',
      amparo: '216',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6203-0 | Entrar/sair de fila de veículos estacionados sem dar pref a pedestres/veículos',
      amparo: '217',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7455-0 | Transitar em velocidade superior à máxima permitida em até 20%',
      amparo: '218, I',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7463-0 | Transitar em velocidade superior à máxima permitida em mais de 20% até 50%',
      amparo: '218, II',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7471-0 | Transitar em velocidade superior à máxima permitida em mais de 50%',
      amparo: '218, III',
      gravidade: 'Gravíss 3X',
      valor: 574.62,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6254-0 | Transitar em velocidade inferior à metade da máxima da via, salvo faixa direita',
      amparo: '219',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6262-0 | Deixar de reduzir a veloc qdo se aproximar de passeata/aglomeração/desfile/etc',
      amparo: '220, I',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6270-0 | Deixar de reduzir a veloc onde o trânsito esteja sendo controlado pelo agente',
      amparo: '220, II',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6270-0 | Deixar de reduzir a veloc onde o trânsito esteja sendo controlado pelo agente',
      amparo: '220, II',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6289-1 | Deixar de reduzir a velocidade do veículo ao aproximar-se da guia da calçada',
      amparo: '220, III',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6289-2 | Deixar de reduzir a velocidade do veículo ao aproximar-se do acostamento',
      amparo: '220, III',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6297-0 | Deixar de reduzir velocidade do veículo ao aproximar-se interseção ñ sinalizada',
      amparo: '220, IV',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6300-0 | Deixar reduzir velocidade nas vias rurais cuja faixa domínio não esteja cercada',
      amparo: '220, V',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6319-0 | Deixar de reduzir a velocidade nos trechos em curva de pequeno raio',
      amparo: '220, VI',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6327-0 | Deixar de reduzir veloc ao aproximar local sinaliz advert de obras/trabalhadores',
      amparo: '220, VII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6335-0 | Deixar de reduzir a velocidade sob chuva/neblina/cerração/ventos fortes',
      amparo: '220, VIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6343-0 | Deixar de reduzir a velocidade quando houver má visibilidade',
      amparo: '220, IX',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6351-0 | Deixar de reduzir veloc qdo pavimento se apresentar escorreg/defeituoso/avariado',
      amparo: '220, X',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6360-0 | Deixar de reduzir a velocidade à aproximação de animais na pista',
      amparo: '220, XI',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6378-0 | Deixar de reduzir a velocidade de forma compatível com a segurança, em declive',
      amparo: '220, XII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6386-0 | Deixar de reduzir veloc de forma compatível c/ segurança ao ultrapassar ciclista',
      amparo: '220, XIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6394-1 | Deixar de reduzir a velocidade nas proximidades de escolas',
      amparo: '220, XIV',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6394-2 | Deixar de reduzir a velocidade nas proximidades de hospitais',
      amparo: '220, XIV',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6394-3 | Deixar de reduzir veloc na proxim estação embarque/desembarque passageiros',
      amparo: '220, XIV',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6394-4 | Deixar de reduzir veloc onde haja intensa movimentação de pedestres',
      amparo: '220, XIV',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6408-0 | Portar no veículo placas de identificação em desacordo c/ especif/modelo Contran',
      amparo: '221',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6416-0 | Confec/distribuir/colocar veíc próprio/terceiro placa identif desacordo Contran',
      amparo: '221, § único',
      gravidade: 'Média',
      valor: 85.13,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6424-0 | Deixar de manter ligado em emerg sist ilum vermelha intermitente ainda q parado',
      amparo: '222',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6432-1 | Transitar com farol desregulado perturbando visão outro condutor',
      amparo: '223',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6432-2 | Transitar com o facho de luz alta perturbando visão outro condutor',
      amparo: '223',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6440-0 | Fazer uso do facho de luz alta dos faróis em vias providas de iluminação pública',
      amparo: '224',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6459-1 | Deixar de sinalizar via p/ tornar visível local qdo tiver remover veíc da pista',
      amparo: '225, I',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6459-2 | Deixar de sinalizar a via p/ tornar visível o local qdo permanecer acostamento',
      amparo: '225, I',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6467-0 | Deixar de sinalizar a via p/ tornar visível o local qdo a carga for derramada',
      amparo: '225, II',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6475-0 | Deixar de retirar qualquer objeto utilizado para sinalização temporária da via',
      amparo: '226',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6483-0 | Usar buzina que não a de toque breve como advertência a pedestre ou condutores',
      amparo: '227, I',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6491-0 | Usar buzina prolongada e sucessivamente a qualquer pretexto',
      amparo: '227, II',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6505-0 | Usar buzina entre as vinte e duas e as seis horas',
      amparo: '227, III',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6513-0 | Usar buzina em locais e horários proibidos pela sinalização',
      amparo: '227, IV',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6521-0 | Usar buzina em desacordo c/ os padrões e freqüências estabelecidas pelo Contran',
      amparo: '227, V',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6530-0 | Usar no veículo equip c/ som em volume/freqüência não autorizados pelo Contran',
      amparo: '228',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6548-0 | Usar no veíc alarme/aparelho produz som perturbe sossego púb desac norma Contran',
      amparo: '229',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6556-1 | Conduzir o veículo com o lacre de identificação violado/falsificado',
      amparo: '230, I',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6556-2 | Conduzir o veículo com a inscrição do chassi violada/falsificada',
      amparo: '230, I',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6556-3 | Conduzir o veículo com o selo violado/falsificado',
      amparo: '230, I',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6556-4 | Conduzir o veículo com a placa violada/falsificada',
      amparo: '230, I',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6556-5 | Conduzir o veículo com qualquer outro elem de identificação violado/falsificado',
      amparo: '230, I',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6564-0 | Conduzir o veículo transportando passageiros em compartimento de carga',
      amparo: '230, II',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6572-0 | Conduzir o veículo com dispositivo antirradar',
      amparo: '230, III',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6580-0 | Conduzir o veículo sem qualquer uma das placas de identificação',
      amparo: '230, IV',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6599-1 | Conduzir o veículo que não esteja registrado',
      amparo: '230, V',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6599-2 | Conduzir o veículo registrado que não esteja devidamente licenciado',
      amparo: '230, V',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6602-0 | Conduzir o veículo com qualquer uma das placas sem legibilidade e visibilidade',
      amparo: '230, VI',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6610-1 | Conduzir o veículo com a cor alterada',
      amparo: '230, VII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6610-2 | Conduzir o veículo com característica alterada',
      amparo: '230, VII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6629-0 | Conduzir veículo s/ ter sido submetido à inspeção seg veicular, qdo obrigatória',
      amparo: '230, VIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6637-1 | Conduzir o veículo sem equipamento obrigatório',
      amparo: '230, IX',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6637-2 | Conduzir o veículo com equipamento obrigatório ineficiente/inoperante',
      amparo: '230, IX',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6645-0 | Conduzir o veículo com equip obrigatório em desacordo com o estab pelo Contran',
      amparo: '230, X',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6653-1 | Conduzir o veículo com descarga livre',
      amparo: '230, XI',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6653-2 | Conduzir o veículo com silenciador de motor defeituoso/deficiente/inoperante',
      amparo: '230, XI',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6661-0 | Conduzir o veículo com equipamento ou acessório proibido',
      amparo: '230, XII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6670-0 | Conduzir o veículo c/ equip do sistema de iluminação e de sinalização alterados',
      amparo: '230, XIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6688-0 | Conduzir veíc c/ registrador instan inalt de velocidade/tempo viciado/defeituoso',
      amparo: '230, XIV',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6696-1 | Conduzir c/ inscr/adesivo/legenda/símbolo afixado pára-brisa e extensão traseira',
      amparo: '230, XV',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6696-2 | Conduzir c/ inscr/adesivo/legenda/símbolo pintado pára-brisa e extensão traseira',
      amparo: '230, XV',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6700-0 | Conduzir veíc com vidro total/parcialmente coberto por película, painéis/pintura',
      amparo: '230, XVI',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6718-0 | Conduzir o veículo com cortinas ou persianas fechadas',
      amparo: '230, XVII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6726-1 | Conduzir o veículo em mau estado de conservação, comprometendo a segurança',
      amparo: '230, XVIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6726-2 | Conduzir o veículo reprovado na avaliação de inspeção de segurança',
      amparo: '230, XVIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6726-3 | Conduzir o veículo reprovado na avaliação de emissão de poluentes e ruído',
      amparo: '230, XVIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6734-0 | Conduzir o veículo sem acionar o limpador de pára-brisa sob chuva',
      amparo: '230, XIX',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6742-0 | Conduzir o veículo sem portar a autorização para condução de escolares',
      amparo: '230, XX',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6750-0 | Conduzir o veíc de carga c/ falta inscrição da tara e demais previstas no CTB',
      amparo: '230, XXI',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6769-0 | Conduzir veíc c/ defeito no sist de iluminação, sinaliz ou lâmpadas queimadas',
      amparo: '230, XXII',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '7560-0 | Conduzir veíc de transp passag ou carga em desacordo c/ as cond do art 67-C CTB',
      amparo: '230, XXIII',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6777-0 | Transitar com o veículo danificando a via, suas instalações e equipamentos',
      amparo: '231, I',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6785-1 | Transitar com veículo derramando a carga que esteja transportando',
      amparo: '231, II, a',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6785-2 | Transitar com veículo lançando a carga que esteja transportando',
      amparo: '231, II, a',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6785-3 | Transitar com veículo arrastando a carga que esteja transportando',
      amparo: '231, II, a',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6793-0 | Transitar com veíc derramando/lançando combustível/lubrif que esteja utilizando',
      amparo: '231, II, b',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6807-0 | Transitar c/veíc derraman/lançando/arrastando objeto possa acarretar risco acid',
      amparo: '231, II, c',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6815-0 | Transitar com veículo produzindo fumaça, gases ou partículas em desac c/ Contran',
      amparo: '231, III',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6823-1 | Transitar c/ veíc e/ou carga c/ dimensões superiores limite legal s/ autorização',
      amparo: '231, IV',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6823-2 | Transitar c/ veíc e/ou carga c/ dimensões superiores est p/sinalização s/autoriz',
      amparo: '231, IV',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6831-1 | Transitar com o veículo com excesso de peso PBT/PBTC',
      amparo: '231, V',
      gravidade: 'Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6831-2 | Transitar com o veículo com excesso de peso - Por Eixo',
      amparo: '231, V',
      gravidade: 'Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6831-3 | Transitar com o veículo com excesso de peso - PBT/PBTC e Por Eixo',
      amparo: '231, V',
      gravidade: 'Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6840-1 | Transitar em desacordo c/ autorização expedida p/veículo c/ dimensões excedentes',
      amparo: '231, VI',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6840-2 | Transitar com autorização vencida, expedida p/ veículo c/ dimensões excedentes',
      amparo: '231, VI',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6858-0 | Transitar com o veículo com lotação excedente',
      amparo: '231, VII',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '6866-1 | Transitar efetuando transporte remunerado de pessoas qdo ñ licenciado p/esse fim',
      amparo: '231, VIII',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '6866-2 | Transitar efetuando transporte remunerado de bens qdo não licenciado p/ esse fim',
      amparo: '231, VIII',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '6874-1 | Transitar com o veículo desligado em declive',
      amparo: '231, IX',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6874-2 | Transitar com o veículo desengrenado em declive',
      amparo: '231, IX',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6882-0 | Transitar com o veículo excedendo a CMT em até 600 kg',
      amparo: '231, X',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6890-0 | Transitar com o veículo excedendo a CMT entre 601 e 1.000 kg',
      amparo: '231, X',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6904-0 | Transitar com o veículo excedendo a CMT acima de 1.000 kg',
      amparo: '231, X',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6912-0 | Conduzir veículo sem os documentos de porte obrigatório referidos no CTB',
      amparo: '232',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6920-1 | Deixar de efetuar registro do veículo em 30 dias, qdo for transf a propriedade',
      amparo: '233 c/c 123, I',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL',
    },
    {
      codDescricao: '6920-2 | Deixar de efetuar reg do veíc em 30 dias, qdo mudar o munic de domicilio/resid',
      amparo: '233 c/c 123, II',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL',
    },
    {
      codDescricao: '6920-3 | Deixar de efetuar reg de veíc em 30 dias, qdo for alterada qquer caract do veic',
      amparo: '233 c/c 123, III',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL',
    },
    {
      codDescricao: '6920-4 | Deixar de efetuar registro de veículo em 30 dias, qdo houver mudança de categoria',
      amparo: '233 c/c 123, IV',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL',
    },
    {
      codDescricao: '6939-1 | Falsificar ou adulterar documento de habilitação',
      amparo: '234',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6939-2 | Falsificar ou adulterar documento de identificação do veículo',
      amparo: '234',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6947-1 | Conduzir pessoas nas partes externas do veículo',
      amparo: '235',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6947-2 | Conduzir animais nas partes externas do veículo',
      amparo: '235',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6947-3 | Conduzir carga nas partes externas do veículo',
      amparo: '235',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6955-0 | Rebocar outro veículo com cabo flexível ou corda',
      amparo: '236',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '6963-0 | Trans c/veíc desac c/especificação/falta de inscr/simbologia necessária identif',
      amparo: '237',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6971-0 | Recusar-se a entregar CNH/CRV/CRLV/ outros documentos',
      amparo: '238',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '6980-0 | Retirar do local veículo legalmente retido para regularização, sem permissão',
      amparo: '239',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '6998-0 | Deixar responsável de promover baixa registro de veíc irrecuperável/desmontado',
      amparo: '240',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL',
    },
    {
      codDescricao: '7005-1 | Deixar de atualizar o cadastro de registro do veículo',
      amparo: '241',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'ESTADUAL',
    },
    {
      codDescricao: '7005-2 | Deixar de atualizar o cadastro de habilitação do condutor',
      amparo: '241',
      gravidade: '3 - Leve',
      valor: 53.20,
      competencia: 'ESTADUAL',
    },
    {
      codDescricao: '7013-1 | Fazer falsa declaração de domicílio para fins de registro/licenciamento',
      amparo: '242',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL',
    },
    {
      codDescricao: '7013-2 | Fazer falsa declaração de domicílio para fins de habilitação',
      amparo: '242',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL',
    },
    {
      codDescricao: '7021-0 | Deixar seguradora de comunicar ocorrência perda total veíc e devolver placas/doc',
      amparo: '243',
      gravidade: 'Grave',
      valor: 127.69,
      competencia: 'ESTADUAL',
    },
    {
      codDescricao: '7030-1 | Conduzir motocicleta, motoneta e ciclomotor sem capacete de segurança',
      amparo: '244, I',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '7030-3 | Conduzir motocicleta, motoneta e ciclomotor sem vestuário aprovado pelo Contran',
      amparo: '244, I',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '7048-1 | Conduzir motocicleta, motoneta e ciclomotor tansportando passageiro s/ capacete',
      amparo: '244, II',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7048-3 | Conduzir motocicleta/motoneta/ciclomotor transportando pas. fora do assento',
      amparo: '244, II',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7056-1 | Conduzir motoc/moton/ciclomotor fazendo malabarismo/equilibrando-se em uma roda',
      amparo: '244, III',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7056-2 | Conduzir ciclo fazendo malabarismo ou equilibrando-se em uma roda',
      amparo: '244, III c/c § 1º',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7064-0 | Conduzir motocicleta, motoneta e ciclomotor com os faróis apagados',
      amparo: '244, IV',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7072-1 | Conduzir motocicleta/motoneta/ciclomotor transportando criança menor de 7 anos',
      amparo: '244, V',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7072-2 | Conduzir motoc/moton/ciclom transp criança s/ condição cuidar própria segurança',
      amparo: '244, V',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7080-0 | Conduzir motocicleta, motoneta e ciclomotor rebocando outro veículo',
      amparo: '244, VI',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7099-1 | Conduzir motocicleta/motoneta/ciclomotor sem segurar o guidom com ambas as mãos',
      amparo: '244, VII',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7099-2 | Conduzir ciclo sem segurar o guidom com ambas as mãos',
      amparo: '244, VII c/c § 1º',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7102-1 | Conduzir motocicleta, motoneta e ciclomotor transportando carga incompatível',
      amparo: '244, VIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7102-2 | Conduzir ciclo transportando carga incompatível',
      amparo: '244, VIII c/c § 1º',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7102-3 | Conduzir motoc/moton/ transportando carga em desacordo c/ § 2º do Art 139-A CTB',
      amparo: '244, VIII',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7552-1 | Conduzir motoc/moton/ efetuando transp remun mercadoria desac c/ art 139-A CTB',
      amparo: '244, IX',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '7552-2 | Conduzir motoc/moton/ efet transp remun desac normas ativid profic mototaxistas',
      amparo: '244, IX',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '7110-0 | Conduzir ciclo transportando passageiro fora da garupa/assento a ele destinado',
      amparo: '244, § 1º, a',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7129-1 | Conduzir ciclo via de trâns rápido ou rodovia salvo se houver acostam/fx própria',
      amparo: '244, § 1º, b',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7137-0 | Conduzir ciclo transportando criança s/ condição de cuidar própria segurança',
      amparo: '244, § 1º, c',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7129-2 | Conduzir ciclomotor em via de trânsito rápido',
      amparo: '244, § 2º',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7129-3 | Conduzir ciclomotor em rodovia salvo se houver acostamento ou faixa própria',
      amparo: '244, § 2º',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7145-0 | Utilizar a via para depósito de mercadorias, materiais ou equipamentos',
      amparo: '245',
      gravidade: 'Grave',
      valor: 127.69,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7153-1 | Deixar de sinalizar obstáculo à circulação/segurança calçada/pista-s/agravamento',
      amparo: '246',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7153-2 | Obstaculizar a via indevidamente-s/agravamento',
      amparo: '246',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7161-1 | Deixar de sinalizar obstáculo circulação/segurança calçada/pista-agravamento 2X',
      amparo: '246',
      gravidade: 'Gravíss 2X',
      valor: 383.08,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7161-2 | Obstaculizar a via indevidamente-agravamento 2X',
      amparo: '246',
      gravidade: 'Gravíss 2X',
      valor: 383.08,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7170-1 | Deixar de sinalizar obstáculo circulação/segurança calçada/pista-agravamento 3X',
      amparo: '246',
      gravidade: 'Gravíss 3X',
      valor: 574.62,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7170-2 | Obstaculizar a via indevidamente-agravamento 3X',
      amparo: '246',
      gravidade: 'Gravíss 3X',
      valor: 574.62,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7188-1 | Deixar de sinalizar obstáculo circulação/segurança calçada/pista-agravamento 4X',
      amparo: '246',
      gravidade: 'Gravíss 4X',
      valor: 766.16,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7188-2 | Obstaculizar a via indevidamente-agravamento 4X',
      amparo: '246',
      gravidade: 'Gravíss 4X',
      valor: 766.16,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7196-1 | Deixar de sinalizar obstáculo circulação/segurança calçada/pista-agravamento 5X',
      amparo: '246',
      gravidade: 'Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7196-2 | Obstaculizar a via indevidamente-agravamento 5X',
      amparo: '246',
      gravidade: 'Gravíss 5X',
      valor: 957.70,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7200-2 | Deixar de conduzir pelo bordo da pista em fila única veículo de tração animal',
      amparo: '247',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7218-0 | Transportar em veíc destinado transp passageiros carga excedente desac art.109',
      amparo: '248',
      gravidade: '5 - Grave',
      valor: 127.69,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '7226-1 | Deixar de manter acesas à noite as luzes posição qdo o veículo estiver parado',
      amparo: '249',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7226-2 | Deixar de manter acesas à noite as luzes de posição veic fazendo carga/descarga',
      amparo: '249',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7234-0 | Em movimento, deixar de manter acesa a luz baixa durante à noite',
      amparo: '250, I, a',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7242-0 | Em movimento de dia, deixar de manter acesa luz baixa túnel com iluminação públ',
      amparo: '250, I, b',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7250-0 | Em mov, deixar de manter acesa luz baixa veíc transp coletivo faixa/pista excl',
      amparo: '250, I, c',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7269-0 | Em movimento, deixar de manter acesa luz baixa do ciclomotor',
      amparo: '250, I, d',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7277-0 | Em mov deixar de manter acesas luzes de posição sob chuva forte/neblina/cerração',
      amparo: '250, II',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7285-0 | Em movimento, deixar de manter a placa traseira iluminada à noite',
      amparo: '250, III',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7293-0 | Utilizar o pisca-alerta, exceto em imobilizações ou situações de emergência',
      amparo: '251, I',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7307-0 | Utilizar luz alta e baixa intermitente, exceto quando permitido pelo CTB',
      amparo: '251, II',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7315-0 | Dirigir o veículo com o braço do lado de fora',
      amparo: '252, I',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7323-1 | Dirigir o veículo transport pessoas à sua esquerda ou entre os braços e pernas',
      amparo: '252, II',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7323-2 | Dirigir o veículo transport animais à sua esquerda ou entre os braços e pernas',
      amparo: '252, II',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7323-3 | Dirigir o veículo transport volume à sua esquerda ou entre os braços e pernas',
      amparo: '252, II',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7331-0 | Dirigir o veículo com incapacidade física ou mental temporária',
      amparo: '252, III',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7340-0 | Dirigir o veíc usando calçado que ñ se firme nos pés/comprometa utiliz pedais',
      amparo: '252, IV',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7358-0 | Dirigir o veículo com apenas uma das mãos, exceto quando permitido pelo CTB',
      amparo: '252, V',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7366-1 | Dirigir o veículo utilizando-se de fones nos ouvidos conec a aparelhagem sonora',
      amparo: '252, VI',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '7366-2 | Dirigir veículo utilizando-se de telefone celular',
      amparo: '252, VI',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '7595-0 | Dirigir veículo realizando cobrança de tarifa com veículo em movimento',
      amparo: '252, VII',
      gravidade: 'Média',
      valor: 85.13,
      competencia: 'ESTAD/MUNIC/RODOV',
    },
    {
      codDescricao: '7374-0 | Bloquear a via com veículo',
      amparo: '253',
      gravidade: '7 - Gravíss',
      valor: 191.54,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7617-1 | Usar veículo para, deliberadamente, interromper a circulação na via',
      amparo: '253-A',
      gravidade: 'Gravíss 30X',
      valor: 5746.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7617-2 | Usar veículo para, deliberadamente, restringir a circulação na via',
      amparo: '253-A',
      gravidade: 'Gravíss 30X',
      valor: 5746.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7617-3 | Usar veículo para, deliberadamente, perturbar a circulação na via',
      amparo: '253-A',
      gravidade: 'Gravíss 30X',
      valor: 5746.20,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7609-0 | Organizar as condutas previstas no caput do art. 253-A',
      amparo: '253-A, § 1º',
      gravidade: 'Gravíss 100X',
      valor: 19154.00,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7382-0 | É proib ao pedestre permanecer/andar pista, exceto p/ cruzá-las onde permitido',
      amparo: '254, I',
      gravidade: '3 - Leve 50%',
      valor: 26.60,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7390-1 | É proibido ao pedestre cruzar pista de rolamento de viaduto exc onde permitido',
      amparo: '254, II',
      gravidade: '3 - Leve 50%',
      valor: 26.60,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7390-2 | É proibido ao pedestre cruzar pista de rolamento de ponte exceto onde permitido',
      amparo: '254, II',
      gravidade: '3 - Leve 50%',
      valor: 26.60,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7390-3 | É proibido ao pedestre cruzar pista de rolamento de túneis exceto onde permitido',
      amparo: '254, II',
      gravidade: '3 - Leve 50%',
      valor: 26.60,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7404-0 | É proib ao pedestre atravessar via área cruzamento exc onde permitido p/ sinaliz',
      amparo: '254, III',
      gravidade: '3 - Leve 50%',
      valor: 26.60,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7412-0 | É proib pedestre utilizar via em agrupam que perturbe trâns/prát esporte/desfile',
      amparo: '254, IV',
      gravidade: '3 - Leve 50%',
      valor: 26.60,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7420-1 | É proibido ao pedestre andar fora da faixa própria',
      amparo: '254, V',
      gravidade: '3 - Leve 50%',
      valor: 26.60,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7420-2 | É proibido ao pedestre andar fora da passarela',
      amparo: '254, V',
      gravidade: '3 - Leve 50%',
      valor: 26.60,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7420-3 | É proibido ao pedestre andar fora da passagem aérea',
      amparo: '254, V',
      gravidade: '3 - Leve 50%',
      valor: 26.60,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7420-4 | É proibido ao pedestre andar fora da passagem subterrânea',
      amparo: '254, V',
      gravidade: '3 - Leve 50%',
      valor: 26.60,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7439-0 | É proibido ao pedestre desobedecer a sinalização de trânsito específica',
      amparo: '254, VI',
      gravidade: '3 - Leve 50%',
      valor: 26.60,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7447-1 | Conduzir bicicleta em passeios onde não seja permitida a circulação desta',
      amparo: '255',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7447-2 | Conduzir bicicleta de forma agressiva',
      amparo: '255',
      gravidade: '4 - Média',
      valor: 85.13,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '5002-0 | Multa, por não identificação do condutor infrator, imposta à pessoa jurídica',
      amparo: '257, § 8º',
      gravidade: '---',
      valor: 0,
      competencia: 'MUNICIPAL/RODOV',
    },
    {
      codDescricao: '7579-0 | Cond que se recusar a se submeter a qq dos proc prev no art. 277 do CTB',
      amparo: '277, § 3º, c/c 165',
      gravidade: 'Gravíss 10X',
      valor: 1915.40,
      competencia: 'ESTADUAL/RODOV',
    },
    {
      codDescricao: '7544-1 | Falta de escrituração livro registro entrada/saída e de uso placa de experiência',
      amparo: '330, § 5º',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL',
    },
    {
      codDescricao: '7544-2 | Atraso escrituração livro registro entrada/saída e de uso placa de experiência',
      amparo: '330, § 5º',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL',
    },
    {
      codDescricao: '7544-3 | Fraude escrituração livro registro entrada/saída e de uso placa de experiência',
      amparo: '330, § 5º',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL',
    },
    {
      codDescricao: '7544-4 | Recusa da exibição do livro registro entrada/saída e de uso placa de experiência',
      amparo: '330, § 5º',
      gravidade: 'Gravíss',
      valor: 191.54,
      competencia: 'ESTADUAL',
    }
  ];

  getAllCodigos() {
    return this.codigos;
  }


}
